# Sorts after the packaged 10-crio.conf.
[crio.runtime]
selinux = true
cgroup_manager = "systemd"

[crio.network]
# /opt/cni/bin: written by the cluster CNI DaemonSet; /usr/libexec/cni: image-owned
plugin_dirs = ["/opt/cni/bin", "/usr/libexec/cni"]

[crio.metrics]
enable_metrics = true
metrics_host = "127.0.0.1"
metrics_port = 9537
